name = "goenchan-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SHARED_MAPPINGS"
id = "8066403859bb407c9e602d1ff2cbc58f"

[env.production]
routes = [
  { pattern = "api.goenchan.com/*", zone_name = "goenchan.com" }
]

[env.development]
# Development environment runs locally
