name = "goenchan-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "api.goenchan.com/*", zone_name = "goenchan.com" }
]

[env.development]
# Development environment runs locally
